### ISSUE TITLE
Fix diode part number

### ISSUE THREAD

**Issue by jeanthom** [jeanthom/Otter-Iron-PRO-BOM#3]
The chosen P/N for the diode is a THT component. Vishay B140-E3/61T should be the right component to use.

**Comment by jeanthom** [comment]
This diode is too big for the PCB.

**Comment by ElRoberto538** [comment]
Hi, thanks for making the parts list. Did you manage to figure out which diode to use?

**Comment by jeanthom** [comment]
Nope, I went with the B140-E3/61T anyway, scrapping the soldermask to make it fit.

**Comment by jeanthom** [comment]
@Jan--Henrik What P/N did you use?

**Comment by ElRoberto538** [comment]
@jeanthom Found it, it is listed in the BOM csv for the normal Otter Iron, the part number is listed incorrectly but the LCSC part number gives the correct diode.

https://lcsc.com/product-detail/Schottky-Barrier-Diodes-SBD_MDD-Microdiode-Electronics-DSK210-K210_C64891.html

**Comment by jeanthom** [comment]
Fixed in git repo, thank for your help
