### ISSUE TITLE
Mosfet is no longer available

### ISSUE THREAD

**Issue by ElRoberto538** [jeanthom/Otter-Iron-PRO-BOM#5]
Seems the mosfet DMP3017SFG-7 (LCSC C461072) is no longer produced, I ordered the manufacturer recommended replacement DMP3013SFV-7 (LCSC C264098). The replacement seems marginally better and about 40% cheaper.

**Comment by Jana-Marie** [comment]
Hey, thanks for your input, I updated the BOM! :)
